'use strict';

/* @ngInject */
function Configuration($stateProvider, $urlRouterProvider, $locationProvider, RestangularProvider, uiSelectConfig, cfpLoadingBarProvider) {
  $urlRouterProvider.otherwise('/');
  $locationProvider.html5Mode(true);
  RestangularProvider.setDefaultHttpFields({cache: true});
  uiSelectConfig.theme = 'bootstrap';
  cfpLoadingBarProvider.includeBar = false;

  $stateProvider
    .state('media', {
      url: "/{media:facebook|twitter}",
      abstract: true
    });
}

/* @ngInject */
function Run($rootScope, $state) {
  $rootScope.$on('$stateChangeStart' , (evt, to, params) => {
    if (to.redirectTo) {
      evt.preventDefault();
      $state.go(to.redirectTo, params);
    }
  });
}

var externalModules = [
  'ngCookies',
  'ngSanitize',
  'ngAnimate',
  'restangular',
  'ui.bootstrap',
  'ui.router',
  'ui.select',
  'toaster',
  'angular-loading-bar',


  // html templates in $templateCache generated by Gulp:
  require('../../.tmp/templates').name,

  require('../components').name,

  require('./common').name,

  // contents modules
  require('./front/front.app').name,
  require('./stats/stats.app').name
];


module.exports = angular
  .module(config.names.app, externalModules)
  .config(Configuration)
  .run(Run);
